### ISSUE TITLE
🚀 02 GitHub Actions — wasm build & cache `setup/15-ci-pipeline`

### ISSUE THREAD

**Issue by xdanger** [xdanger/tower-tumbler#15]
## 🎯 任务目标

配置完整的 CI/CD 流水线，实现自动化构建、测试、优化和部署，确保代码质量和快速迭代。

## 📋 前置条件

- [x] 项目基础结构 (#4)
- [ ] 了解 GitHub Actions
- [ ] 熟悉 WASM 优化流程
- [ ] 理解多环境部署策略

### 1. GitHub Actions 主工作流

```yaml
# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # 代码质量检查
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Check formatting
        run: cargo fmt -- --check
      
      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings
      
      - name: Check documentation
        run: cargo doc --no-deps --all-features

  # 单元测试
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run tests
        run: cargo test --all-features
      
      - name: Run doc tests
        run: cargo test --doc

  # WASM 构建
  build-wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      
      - name: Install wasm-opt
        run: |
          npm install -g wasm-opt
      
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            dist/
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build release
        run: |
          trunk build --release
          
      - name: Optimize WASM
        run: |
          wasm-opt -Oz \
            -o dist/optimized.wasm \
            dist/*.wasm
          mv dist/optimized.wasm dist/tower-tumbler_bg.wasm
      
      - name: Check bundle size
        run: |
          SIZE=$(stat -c%s dist/*.wasm)
          echo "WASM size: $SIZE bytes"
          if [ $SIZE -gt 3145728 ]; then
            echo "::warning::WASM size exceeds 3MB limit"
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wasm-dist
          path: dist/
          retention-days: 7

  # E2E 测试
  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build-wasm
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      
      - name: Download WASM artifacts
        uses: actions/download-artifact@v3
        with:
          name: wasm-dist
          path: dist/
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Playwright
        run: |
          npm install -D @playwright/test
          npx playwright install --with-deps ${{ matrix.browser }}
      
      - name: Start test server
        run: |
          python -m http.server 8080 --directory dist &
          sleep 5
      
      - name: Run E2E tests
        run: |
          npx playwright test --browser=${{ matrix.browser }}
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results-${{ matrix.browser }}
          path: test-results/

  # 性能测试
  performance:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - uses: actions/checkout@v4
      
      - name: Download WASM artifacts
        uses: actions/download-artifact@v3
        with:
          name: wasm-dist
          path: dist/
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:8080
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./.github/lighthouse/lighthouserc.js

  # 部署到 GitHub Pages
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-wasm, e2e-test]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download WASM artifacts
        uses: actions/download-artifact@v3
        with:
          name: wasm-dist
          path: dist/
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/
      
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

### 2. Pull Request 工作流

```yaml
# .github/workflows/pr.yml
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # PR 大小检查
  size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check PR size
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const total = additions + deletions;
            
            if (total > 1000) {
              core.warning(`Large PR detected: +${additions} -${deletions}`);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '⚠️ This PR contains ' + total + ' changes. Consider breaking it into smaller PRs.'
              });
            }

  # 依赖审计
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run cargo audit
        uses: actions-rust-lang/audit@v1
      
      - name: Check dependencies
        run: |
          cargo tree --duplicate
          cargo outdated --exit-code 1 || true
```

### 3. 性能基准测试

```yaml
# .github/workflows/benchmark.yml
name: Performance Benchmark

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Run benchmarks
        run: |
          cargo bench --all-features | tee output.txt
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
```

### 4. E2E 测试配置

```javascript
// playwright.config.js
module.exports = {
  testDir: './tests/e2e',
  timeout: 30000,
  retries: 2,
  workers: 1,
  
  use: {
    baseURL: 'http://localhost:8080',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'on-first-retry',
  },
  
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
    },
  ],
};
```

### 5. E2E 测试用例

```javascript
// tests/e2e/gameplay.spec.js
const { test, expect } = require('@playwright/test');

test.describe('Tower Tumbler Gameplay', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await page.waitForLoadState('networkidle');
  });
  
  test('should load game successfully', async ({ page }) => {
    // 检查 canvas 元素
    const canvas = await page.locator('canvas');
    await expect(canvas).toBeVisible();
    
    // 检查 WebGL 上下文
    const hasWebGL = await page.evaluate(() => {
      const canvas = document.querySelector('canvas');
      return \!\!(canvas.getContext('webgl2') || canvas.getContext('webgl'));
    });
    expect(hasWebGL).toBe(true);
  });
  
  test('should start game on button click', async ({ page }) => {
    // 点击开始按钮
    await page.click('text=开始游戏');
    
    // 验证游戏状态
    await expect(page.locator('.game-hud')).toBeVisible();
    await expect(page.locator('.score-display')).toContainText('0');
  });
  
  test('should handle device orientation', async ({ page, context }) => {
    // 授予权限
    await context.grantPermissions(['accelerometer', 'gyroscope']);
    
    // 模拟设备倾斜
    await page.evaluate(() => {
      window.dispatchEvent(new DeviceOrientationEvent('deviceorientation', {
        alpha: 0,
        beta: 30,
        gamma: 0
      }));
    });
    
    // 验证重力变化
    await page.waitForTimeout(100);
    // 检查箱子是否按预期移动
  });
  
  test('should handle game over', async ({ page }) => {
    // 触发游戏结束
    // ...
    
    // 验证游戏结束界面
    await expect(page.locator('.game-over-screen')).toBeVisible();
    await expect(page.locator('text=游戏结束')).toBeVisible();
  });
});
```

### 6. Lighthouse 性能配置

```javascript
// .github/lighthouse/lighthouserc.js
module.exports = {
  ci: {
    collect: {
      staticDistDir: './dist',
      numberOfRuns: 3,
    },
    assert: {
      preset: 'lighthouse:no-pwa',
      assertions: {
        'categories:performance': ['error', { minScore: 0.8 }],
        'categories:accessibility': ['warn', { minScore: 0.9 }],
        'categories:best-practices': ['warn', { minScore: 0.9 }],
        'categories:seo': ['warn', { minScore: 0.8 }],
        'first-contentful-paint': ['error', { maxNumericValue: 2000 }],
        'interactive': ['error', { maxNumericValue: 3500 }],
        'resource-summary:script:size': ['error', { maxNumericValue: 3000000 }],
        'resource-summary:total:size': ['error', { maxNumericValue: 5000000 }],
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
```

### 7. 发布工作流

```yaml
# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build WASM
        run: |
          trunk build --release
          wasm-opt -Oz -o dist/tower-tumbler.wasm dist/*.wasm
      
      - name: Create archive
        run: |
          cd dist
          zip -r ../tower-tumbler-${{ github.ref_name }}.zip .
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tower-tumbler-${{ github.ref_name }}.zip
          asset_name: tower-tumbler-${{ github.ref_name }}.zip
          asset_content_type: application/zip
```

## 📊 验收标准

1. **构建流程**
   - [ ] 代码提交自动触发构建
   - [ ] 构建时间 < 5 分钟
   - [ ] 缓存命中率 > 80%
   - [ ] WASM 优化正常工作

2. **测试覆盖**
   - [ ] 单元测试通过率 100%
   - [ ] E2E 测试覆盖主要流程
   - [ ] 多浏览器兼容性测试
   - [ ] 性能基准测试稳定

3. **部署流程**
   - [ ] 主分支自动部署
   - [ ] 部署时间 < 2 分钟
   - [ ] 部署零宕机
   - [ ] 回滚机制可用

4. **监控告警**
   - [ ] 构建失败及时通知
   - [ ] 性能退化告警
   - [ ] Bundle size 监控
   - [ ] 错误率监控

## 🚧 潜在问题

1. **构建时间**
   - Rust 编译慢
   - 需要优化缓存策略

2. **测试稳定性**
   - WASM 测试环境复杂
   - 需要重试机制

3. **资源限制**
   - GitHub Actions 限制
   - 需要优化并行度

## 📝 开发笔记

- 考虑添加 PR 预览环境
- 集成代码覆盖率报告
- 添加性能趋势图表

## 🔗 参考资源

- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Trunk Build Tool](https://trunkrs.dev/)
- [Playwright Testing](https://playwright.dev/)
- [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci)

---

**任务类型**: 🏗️ Infrastructure
**预计工时**: 4-5 小时
**依赖任务**: 基础项目结构
**优先级**: 🟡 Medium (支撑开发流程)
