### ISSUE TITLE
⚡ 13 脚本运行 wasm-opt -Oz + brotli `perf/20-wasm-opt`

### ISSUE THREAD

**Issue by xdanger** [xdanger/tower-tumbler#20]
## 📋 概述

本任务旨在创建自动化的 WASM 优化脚本，通过 wasm-opt 和 Brotli 压缩技术，显著减少 WASM 文件大小，提升加载性能。目标是将最终的 WASM 文件控制在 2.3MB（gzip）以内。

## 🎯 目标

1. **自动化优化流程**
   - 集成 wasm-opt 优化
   - 实现 Brotli 压缩
   - 生成多种压缩格式

2. **性能指标监控**
   - 跟踪文件大小变化
   - 测量优化时间
   - 记录压缩率

3. **CI/CD 集成**
   - 自动运行优化
   - 生成优化报告
   - 缓存优化结果

### 1. 优化脚本实现

```bash
#\!/bin/bash
# scripts/optimize-wasm.sh

set -e

# 配置
WASM_FILE="./dist/tower_tumbler_bg.wasm"
OPTIMIZED_DIR="./dist/optimized"
STATS_FILE="./dist/optimization-stats.json"

# 颜色输出
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Starting WASM optimization...${NC}"

# 创建输出目录
mkdir -p "$OPTIMIZED_DIR"

# 获取原始文件大小
ORIGINAL_SIZE=$(stat -f%z "$WASM_FILE" 2>/dev/null || stat -c%s "$WASM_FILE")
echo "Original size: $(($ORIGINAL_SIZE / 1024 / 1024))MB ($ORIGINAL_SIZE bytes)"

# 运行 wasm-opt 优化
echo -e "\n${YELLOW}Running wasm-opt...${NC}"
time wasm-opt \
  -Oz \
  --enable-simd \
  --enable-bulk-memory \
  --strip-debug \
  --strip-dwarf \
  --strip-producers \
  --strip-target-features \
  --converge \
  "$WASM_FILE" \
  -o "$OPTIMIZED_DIR/tower_tumbler_bg.wasm"

# 获取优化后大小
OPTIMIZED_SIZE=$(stat -f%z "$OPTIMIZED_DIR/tower_tumbler_bg.wasm" 2>/dev/null || stat -c%s "$OPTIMIZED_DIR/tower_tumbler_bg.wasm")
echo "Optimized size: $(($OPTIMIZED_SIZE / 1024 / 1024))MB ($OPTIMIZED_SIZE bytes)"
echo "Reduction: $(( ($ORIGINAL_SIZE - $OPTIMIZED_SIZE) * 100 / $ORIGINAL_SIZE ))%"

# Gzip 压缩
echo -e "\n${YELLOW}Creating gzip version...${NC}"
gzip -9 -k -f "$OPTIMIZED_DIR/tower_tumbler_bg.wasm"
GZIP_SIZE=$(stat -f%z "$OPTIMIZED_DIR/tower_tumbler_bg.wasm.gz" 2>/dev/null || stat -c%s "$OPTIMIZED_DIR/tower_tumbler_bg.wasm.gz")
echo "Gzip size: $(($GZIP_SIZE / 1024 / 1024))MB ($GZIP_SIZE bytes)"

# Brotli 压缩
echo -e "\n${YELLOW}Creating brotli version...${NC}"
brotli -9 -k -f "$OPTIMIZED_DIR/tower_tumbler_bg.wasm"
BROTLI_SIZE=$(stat -f%z "$OPTIMIZED_DIR/tower_tumbler_bg.wasm.br" 2>/dev/null || stat -c%s "$OPTIMIZED_DIR/tower_tumbler_bg.wasm.br")
echo "Brotli size: $(($BROTLI_SIZE / 1024 / 1024))MB ($BROTLI_SIZE bytes)"

# 生成统计信息
cat > "$STATS_FILE" << EOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "original": {
    "size": $ORIGINAL_SIZE,
    "size_mb": $(echo "scale=2; $ORIGINAL_SIZE / 1024 / 1024" | bc)
  },
  "optimized": {
    "size": $OPTIMIZED_SIZE,
    "size_mb": $(echo "scale=2; $OPTIMIZED_SIZE / 1024 / 1024" | bc),
    "reduction_percent": $(( ($ORIGINAL_SIZE - $OPTIMIZED_SIZE) * 100 / $ORIGINAL_SIZE ))
  },
  "gzip": {
    "size": $GZIP_SIZE,
    "size_mb": $(echo "scale=2; $GZIP_SIZE / 1024 / 1024" | bc),
    "reduction_percent": $(( ($ORIGINAL_SIZE - $GZIP_SIZE) * 100 / $ORIGINAL_SIZE ))
  },
  "brotli": {
    "size": $BROTLI_SIZE,
    "size_mb": $(echo "scale=2; $BROTLI_SIZE / 1024 / 1024" | bc),
    "reduction_percent": $(( ($ORIGINAL_SIZE - $BROTLI_SIZE) * 100 / $ORIGINAL_SIZE ))
  }
}
EOF

echo -e "\n${GREEN}✅ Optimization complete\!${NC}"
echo "Stats saved to: $STATS_FILE"

# 检查目标大小
if [ $GZIP_SIZE -gt 2411520 ]; then # 2.3MB in bytes
  echo -e "\n${YELLOW}⚠️  Warning: Gzip size exceeds 2.3MB target\!${NC}"
  exit 1
fi
```

### 2. Rust 构建配置优化

```toml
# Cargo.toml
[profile.release]
opt-level = "z"     # 优化大小
lto = true          # 链接时优化
codegen-units = 1   # 单一代码生成单元
strip = true        # 移除符号
panic = "abort"     # 简化 panic 处理

[profile.wasm]
inherits = "release"
opt-level = "z"
lto = "fat"
# wasm-opt 会处理这些，所以这里不需要
# strip = false     
# debug = false

# 条件编译减少代码
[features]
default = []
debug = ["bevy/trace"]

# 依赖优化
[dependencies.bevy]
version = "0.14"
default-features = false
features = [
  "bevy_asset",
  "bevy_core_pipeline", 
  "bevy_render",
  "bevy_sprite",
  "bevy_ui",
  "bevy_winit",
  "webgl2",
  # 不需要的功能不包含
]
```

### 3. 构建脚本增强

```rust
// build.rs
use std::process::Command;

fn main() {
    // 仅在 WASM 目标时运行
    if std::env::var("TARGET").unwrap().contains("wasm32") {
        optimize_for_wasm();
    }
}

fn optimize_for_wasm() {
    println\!("cargo:rerun-if-env-changed=WASM_OPT_LEVEL");
    
    // 设置 rustflags
    println\!("cargo:rustc-link-arg=-zstack-size=1048576"); // 1MB stack
    println\!("cargo:rustc-link-arg=--import-memory");
    println\!("cargo:rustc-link-arg=--initial-memory=4194304"); // 4MB
    println\!("cargo:rustc-link-arg=--max-memory=16777216"); // 16MB
    
    // 条件编译标志
    println\!("cargo:rustc-cfg=web_sys_unstable_apis");
}
```

### 4. Trunk 配置优化

```toml
# Trunk.toml
[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
ignore = ["dist", "target"]

[serve]
address = "127.0.0.1"
port = 8080

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "./scripts/optimize-wasm.sh"]

[[hooks]]
stage = "post_build" 
command = "sh"
command_arguments = ["-c", "cp dist/optimized/* dist/"]
```

### 5. 服务器配置

```nginx
# nginx.conf - 支持 Brotli
server {
    listen 80;
    server_name game.example.com;
    root /var/www/tower-tumbler;
    
    # Brotli 支持
    brotli on;
    brotli_static on;
    brotli_types application/wasm;
    
    # WASM 内容类型
    location ~ \.wasm$ {
        add_header Content-Type application/wasm;
        add_header Content-Encoding br;
        
        # 优先提供 .br 文件
        try_files $uri.br $uri.gz $uri =404;
    }
    
    # 缓存策略
    location ~* \.(wasm|js|css)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
```

### 6. CI 集成

```yaml
# .github/workflows/optimize.yml
name: WASM Optimization

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  optimize:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    
    - name: Install wasm-opt
      run: |
        npm install -g wasm-opt
        
    - name: Install brotli
      run: |
        sudo apt-get update
        sudo apt-get install -y brotli
    
    - name: Cache WASM tools
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/
          ~/.cargo/git/
          target/
        key: ${{ runner.os }}-wasm-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build WASM
      run: |
        cargo build --release --target wasm32-unknown-unknown
        
    - name: Run optimization
      run: |
        ./scripts/optimize-wasm.sh
        
    - name: Upload stats
      uses: actions/upload-artifact@v3
      with:
        name: optimization-stats
        path: dist/optimization-stats.json
        
    - name: Check size limits
      run: |
        GZIP_SIZE=$(stat -c%s dist/optimized/tower_tumbler_bg.wasm.gz)
        if [ $GZIP_SIZE -gt 2411520 ]; then
          echo "Error: WASM size exceeds 2.3MB limit\!"
          exit 1
        fi
```

### 7. 监控和报告

```javascript
// scripts/size-report.js
const fs = require('fs');
const path = require('path');

function generateSizeReport() {
  const stats = JSON.parse(
    fs.readFileSync('./dist/optimization-stats.json', 'utf8')
  );
  
  const report = `
# 📊 WASM Size Report

**Date**: ${stats.timestamp}

## File Sizes

| Format | Size | Reduction |
|--------|------|-----------|
| Original | ${stats.original.size_mb}MB | - |
| Optimized | ${stats.optimized.size_mb}MB | ${stats.optimized.reduction_percent}% |
| Gzip | ${stats.gzip.size_mb}MB | ${stats.gzip.reduction_percent}% |
| Brotli | ${stats.brotli.size_mb}MB | ${stats.brotli.reduction_percent}% |

## Status

${stats.gzip.size_mb <= 2.3 ? '✅ Within 2.3MB target' : '❌ Exceeds 2.3MB target'}
  `;
  
  fs.writeFileSync('./dist/size-report.md', report);
}

generateSizeReport();
```

## 📝 实现步骤

1. **环境准备**
   - [ ] 安装 wasm-opt
   - [ ] 安装 brotli
   - [ ] 配置构建工具

2. **脚本开发**
   - [ ] 创建优化脚本
   - [ ] 添加大小检查
   - [ ] 生成统计报告

3. **构建配置**
   - [ ] 优化 Cargo.toml
   - [ ] 配置 Trunk hooks
   - [ ] 设置条件编译

4. **CI/CD 集成**
   - [ ] 添加 GitHub Actions
   - [ ] 配置缓存策略
   - [ ] 自动化测试

5. **部署配置**
   - [ ] 服务器 Brotli 支持
   - [ ] CDN 配置
   - [ ] 缓存策略

## ✅ 验收标准

1. **大小目标**
   - [ ] Gzip 压缩后 ≤ 2.3MB
   - [ ] Brotli 压缩后 ≤ 2.0MB
   - [ ] 优化时间 < 2 分钟

2. **自动化**
   - [ ] 一键运行优化
   - [ ] CI 自动执行
   - [ ] 自动生成报告

3. **兼容性**
   - [ ] 优化后功能正常
   - [ ] 性能无下降
   - [ ] 跨浏览器兼容

## 🚀 优化技巧

1. **代码层面**
   - 使用 `#[cfg(target_arch = "wasm32")]` 条件编译
   - 避免大型依赖
   - 移除调试代码

2. **构建层面**
   - 使用 `opt-level = "z"`
   - 启用 LTO
   - 单代码生成单元

3. **工具层面**
   - wasm-opt `--converge` 多次优化
   - 探索 `--low-memory-unused` 选项
   - 测试不同压缩级别

## 📊 预期收益

- 加载时间减少 50%+
- 首次渲染时间提升
- 移动端体验改善
- 带宽成本降低
