### ISSUE TITLE
🎨 17 Rustfmt & Clippy 门控 `chore/23-lint-format`

### ISSUE THREAD

**Issue by xdanger** [xdanger/tower-tumbler#23]
## 📋 概述

本任务旨在建立严格的代码质量标准，通过配置 Rustfmt 和 Clippy，确保代码风格一致性和质量。在 CI/CD 流程中强制执行这些标准，防止不符合规范的代码进入主分支。

## 🎯 目标

1. **统一代码风格**
   - 配置 Rustfmt 规则
   - 自动格式化代码
   - 保持风格一致性

2. **提高代码质量**
   - 配置 Clippy 规则
   - 捕获潜在问题
   - 优化代码模式

3. **自动化检查**
   - CI 强制执行
   - Pre-commit hooks
   - IDE 集成配置

### 1. Rustfmt 配置

```toml
# rustfmt.toml
# 基础配置
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# 导入和排序
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# 格式化选项
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# 链式调用
use_field_init_shorthand = true
use_try_shorthand = true
chain_width = 60
single_line_if_else_max_width = 50

# 其他
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
remove_nested_parens = true
overflow_delimited_expr = true

# WASM 特定
# 保持较小的行宽以适应移动设备调试
```

### 2. Clippy 配置

```toml
# .clippy.toml
# 设置 MSRV (Minimum Supported Rust Version)
msrv = "1.75.0"

# 避免过大的函数
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
cognitive-complexity-threshold = 30

# 类型复杂度
type-complexity-threshold = 250
```

```rust
// src/lib.rs 或 main.rs 顶部
#\![warn(
    // Clippy 规则组
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::cargo,
    
    // Rust 编译器 lint
    rust_2018_idioms,
    future_incompatible,
    nonstandard_style,
    
    // 文档
    missing_docs,
    rustdoc::all,
)]
#\![allow(
    // 游戏开发中常见的合理模式
    clippy::module_name_repetitions,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_precision_loss,
    
    // Bevy 特定
    clippy::type_complexity, // Bevy 系统参数可能很复杂
    clippy::too_many_arguments, // Bevy 系统可能有多个参数
    
    // WASM 特定
    clippy::arc_with_non_send_sync, // WASM 是单线程的
)]

// 针对 WASM 的条件配置
#[cfg(target_arch = "wasm32")]
#\![allow(
    clippy::unused_async, // WASM 中某些异步代码可能未使用
)]

//\! # Tower Tumbler
//\! 
//\! 一个基于物理的堆叠游戏，使用设备倾斜控制。
```

### 3. Pre-commit Hook 配置

```bash
#\!/bin/bash
# .git/hooks/pre-commit

set -e

echo "🔍 Running pre-commit checks..."

# 检查格式化
echo "📐 Checking formatting with rustfmt..."
cargo fmt -- --check
if [ $? -ne 0 ]; then
    echo "❌ Code is not properly formatted. Run 'cargo fmt' to fix."
    exit 1
fi

# 运行 Clippy
echo "📎 Running clippy..."
cargo clippy --all-targets --all-features -- -D warnings
if [ $? -ne 0 ]; then
    echo "❌ Clippy found issues. Please fix them before committing."
    exit 1
fi

# 检查 WASM 目标
echo "🎯 Checking WASM target..."
cargo clippy --target wasm32-unknown-unknown -- -D warnings
if [ $? -ne 0 ]; then
    echo "❌ Clippy found WASM-specific issues."
    exit 1
fi

echo "✅ All pre-commit checks passed\!"
```

### 4. CI/CD 集成

```yaml
# .github/workflows/lint.yml
name: Lint and Format

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Check formatting
        run: cargo fmt --all -- --check
        
      - name: Report formatting diff
        if: failure()
        run: cargo fmt --all -- --check --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          "x86_64-unknown-linux-gnu",
          "wasm32-unknown-unknown"
        ]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy
      
      - name: Install dependencies (Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxi-dev libgl1-mesa-dev
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      
      - name: Run Clippy
        run: |
          cargo clippy --target ${{ matrix.target }} \
            --all-features \
            --all-targets \
            -- -D warnings \
            -W clippy::all \
            -W clippy::pedantic \
            -W clippy::nursery \
            -W clippy::cargo
      
      - name: Check benchmarks
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cargo clippy --benches -- -D warnings

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      
      - name: Check documentation
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --all-features
```

### 5. VS Code 配置

```json
// .vscode/settings.json
{
  "editor.formatOnSave": true,
  "rust-analyzer.cargo.features": "all",
  "rust-analyzer.check.command": "clippy",
  "rust-analyzer.check.extraArgs": [
    "--all-targets",
    "--all-features",
    "--",
    "-W",
    "clippy::all",
    "-W",
    "clippy::pedantic"
  ],
  "rust-analyzer.rustfmt.extraArgs": [
    "+nightly"
  ],
  "[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer"
  },
  "files.watcherExclude": {
    "**/target/**": true,
    "**/dist/**": true
  }
}
```

### 6. 项目特定 Lint 规则

```rust
// src/lints.rs
//\! 项目特定的 lint 规则和宏

/// 标记代码为临时解决方案
#[macro_export]
macro_rules\! temporary_workaround {
    ($reason:expr) => {
        #[allow(dead_code)]
        #[doc = concat\!("⚠️ TEMPORARY WORKAROUND: ", $reason)]
        const _: () = ();
    };
}

/// 标记性能关键代码
#[macro_export]
macro_rules\! performance_critical {
    () => {
        #[inline(always)]
        #[allow(clippy::missing_safety_doc)]
    };
}

/// WASM 特定代码标记
#[macro_export]
macro_rules\! wasm_only {
    ($($item:item)*) => {
        $(
            #[cfg(target_arch = "wasm32")]
            $item
        )*
    };
}

// 自定义 derive 宏的 lint 配置
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Debug, Clone, PartialEq)]
pub struct GameConfig {
    // ...
}
```

### 7. 自动修复脚本

```bash
#\!/bin/bash
# scripts/fix-all.sh

set -e

echo "🔧 Running automatic fixes..."

# 格式化代码
echo "📐 Formatting code..."
cargo fmt --all

# 应用 Clippy 修复
echo "📎 Applying clippy fixes..."
cargo clippy --all-targets --all-features --fix --allow-dirty --allow-staged

# WASM 特定修复
echo "🎯 Applying WASM-specific fixes..."
cargo clippy --target wasm32-unknown-unknown --fix --allow-dirty --allow-staged

# 更新依赖
echo "📦 Checking for outdated dependencies..."
cargo update --dry-run

# 清理
echo "🧹 Cleaning up..."
cargo clean -p tower-tumbler

echo "✅ All fixes applied\!"
echo "📝 Please review the changes before committing."
```

### 8. 团队指南文档

```markdown
# 代码风格指南

## 快速开始

1. 安装 pre-commit hook:
   ```bash
   ./scripts/setup-hooks.sh
   ```

2. 配置编辑器（VS Code）:
   - 安装 rust-analyzer 扩展
   - 项目已包含 .vscode/settings.json

3. 运行检查:
   ```bash
   cargo fmt --check
   cargo clippy
   ```

### 1. 类型复杂度
```rust
// ❌ 避免
type ComplexQuery<'w, 's> = Query<'w, 's, (
    &'static Transform,
    &'static Velocity,
    Option<&'static Health>,
    Option<&'static Player>,
)>;

// ✅ 推荐
#[derive(Component)]
struct PhysicsBundle {
    transform: Transform,
    velocity: Velocity,
}
```

### 2. 大函数拆分
```rust
// ❌ 避免：单个巨大函数
fn update_game_state(/* 20 个参数 */) {
    // 200 行代码
}

// ✅ 推荐：拆分为小函数
fn update_game_state(state: &mut GameState) {
    update_physics(state);
    update_scoring(state);
    check_game_over(state);
}
```

## CI 失败排查

1. **格式化失败**：运行 `cargo fmt`
2. **Clippy 警告**：查看具体警告，运行 `cargo clippy --fix`
3. **文档警告**：确保公共 API 都有文档注释
```

## 📝 实现步骤

1. **基础配置**
   - [ ] 创建 rustfmt.toml
   - [ ] 创建 .clippy.toml
   - [ ] 更新项目 lint 配置

2. **工具集成**
   - [ ] 设置 pre-commit hooks
   - [ ] 配置 VS Code
   - [ ] 创建修复脚本

3. **CI/CD 配置**
   - [ ] 添加 lint workflow
   - [ ] 配置缓存策略
   - [ ] 设置必需检查

4. **文档编写**
   - [ ] 编写风格指南
   - [ ] 创建示例代码
   - [ ] 记录最佳实践

5. **团队推广**
   - [ ] 修复现有代码
   - [ ] 团队培训
   - [ ] 建立审查流程

## ✅ 验收标准

1. **自动化程度**
   - [ ] Pre-commit 自动检查
   - [ ] CI 强制执行
   - [ ] 一键修复脚本

2. **覆盖范围**
   - [ ] 所有 Rust 代码
   - [ ] 包括测试代码
   - [ ] WASM 特定检查

3. **开发体验**
   - [ ] 快速反馈
   - [ ] 清晰错误信息
   - [ ] 易于修复

## 🚀 最佳实践

1. **渐进式采用**
   - 先 warning 后 error
   - 逐步提高标准
   - 保留合理例外

2. **性能考虑**
   - 缓存 lint 结果
   - 增量检查
   - 并行执行

3. **团队协作**
   - 统一工具版本
   - 分享配置文件
   - 定期更新规则

## 📊 预期收益

- 减少代码审查时间 40%
- 避免常见错误和性能问题
- 提高代码可读性和一致性
- 新人更快上手项目规范
