### ISSUE TITLE
🚀 21 v0.1.0 标签 + GitHub Pages 部署 `release/26-mvp-tag`

### ISSUE THREAD

**Issue by xdanger** [xdanger/tower-tumbler#26]
## 📋 概述

本任务旨在创建项目的首个正式版本 v0.1.0，并自动化部署到 GitHub Pages。建立完整的发布流程，包括版本标记、WASM 优化、自动部署和监控。

## 🎯 目标

1. **版本发布管理**
   - 创建 v0.1.0 标签
   - 生成 changelog
   - 自动化发布流程

2. **GitHub Pages 部署**
   - 优化 WASM 构建
   - 配置静态托管
   - CDN 和缓存策略

3. **监控和分析**
   - 部署状态监控
   - 性能分析
   - 错误追踪

### 1. 发布工作流配置

```yaml
# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate changelog
        id: changelog
        run: |
          # 生成自上次发布以来的变更日志
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s" --no-merges)
          else
            CHANGELOG=$(git log ${PREVIOUS_TAG}..${{ github.ref }} --pretty=format:"- %s" --no-merges)
          fi
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ## 🎮 Tower Tumbler ${{ steps.get_version.outputs.version }}
            
            ### 🎯 新功能
            - 基于物理的堆叠游戏核心
            - 设备倾斜控制支持
            - 完美叠加得分系统
            - 跨平台兼容性
            
            ### 🔧 技术特性
            - Rust + Bevy + WASM 技术栈
            - Rapier2D 物理引擎
            - 响应式 UI 设计
            - 优化的 WASM 包（< 2.3MB）
            
            ### 📱 支持平台
            - iOS Safari (with permission)
            - Android Chrome
            - Desktop browsers (fallback controls)
            
            ### 🚀 在线试玩
            [立即体验 Tower Tumbler](https://xdanger.github.io/tower-tumbler/)
            
            ### 📋 变更记录
            ${{ steps.changelog.outputs.changelog }}
            
            ### 🐛 已知问题
            - 某些旧版本浏览器可能不支持 WASM
            - iOS 需要用户授权陀螺仪权限
            
          draft: false
          prerelease: false

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Install dependencies
        run: |
          cargo install trunk wasm-bindgen-cli
          npm install -g wasm-opt brotli
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: release-${{ runner.os }}
      
      - name: Build release
        run: |
          trunk build --release
          
      - name: Optimize WASM
        run: |
          ./scripts/optimize-wasm.sh
          
      - name: Generate deployment info
        run: |
          cat > dist/deployment-info.json << EOF
          {
            "version": "${{ needs.create-release.outputs.version }}",
            "build_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "commit": "${{ github.sha }}",
            "workflow_run": "${{ github.run_id }}"
          }
          EOF
          
      - name: Add CNAME for custom domain
        run: |
          echo "tower-tumbler.example.com" > dist/CNAME
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: tower-tumbler.example.com
          
      - name: Upload release assets
        run: |
          # 压缩构建产物
          tar -czf tower-tumbler-${{ needs.create-release.outputs.version }}-wasm.tar.gz -C dist .
          
          # 上传到 release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/gzip" \
            --data-binary @tower-tumbler-${{ needs.create-release.outputs.version }}-wasm.tar.gz \
            "${{ needs.create-release.outputs.upload_url }}?name=tower-tumbler-${{ needs.create-release.outputs.version }}-wasm.tar.gz&label=WASM Build"
```

### 2. 构建优化脚本

```bash
#\!/bin/bash
# scripts/build-release.sh

set -e

echo "🚀 Building Tower Tumbler release..."

# 环境检查
command -v trunk >/dev/null 2>&1 || { echo "❌ trunk is required"; exit 1; }
command -v wasm-opt >/dev/null 2>&1 || { echo "❌ wasm-opt is required"; exit 1; }

# 清理旧构建
rm -rf dist/
rm -rf target/wasm32-unknown-unknown/release/

# 构建发布版本
echo "📦 Building with Trunk..."
trunk build --release

# 优化 WASM
echo "⚡ Optimizing WASM..."
./scripts/optimize-wasm.sh

# 生成构建报告
echo "📊 Generating build report..."
WASM_SIZE=$(stat -c%s dist/tower_tumbler_bg.wasm)
GZIP_SIZE=$(stat -c%s dist/tower_tumbler_bg.wasm.gz)
BROTLI_SIZE=$(stat -c%s dist/tower_tumbler_bg.wasm.br)

cat > dist/build-report.json << EOF
{
  "build_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "sizes": {
    "wasm": $WASM_SIZE,
    "gzip": $GZIP_SIZE,
    "brotli": $BROTLI_SIZE
  },
  "version": "$(git describe --tags --always)"
}
EOF

echo "✅ Build complete\!"
echo "📊 Sizes: WASM=$(($WASM_SIZE/1024/1024))MB, Gzip=$(($GZIP_SIZE/1024/1024))MB, Brotli=$(($BROTLI_SIZE/1024/1024))MB"
```

### 3. 网站配置

```html
<\!-- index.html 生产环境模板 -->
<\!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Tower Tumbler - 物理堆叠游戏</title>
    <meta name="description" content="基于物理的堆叠游戏，使用设备倾斜控制" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    
    <\!-- PWA 支持 -->
    <link rel="manifest" href="manifest.json" />
    <meta name="theme-color" content="#000000" />
    
    <\!-- 预加载关键资源 -->
    <link rel="preload" href="tower_tumbler.js" as="script" />
    <link rel="preload" href="tower_tumbler_bg.wasm" as="fetch" type="application/wasm" crossorigin />
    
    <\!-- SEO 和社交媒体 -->
    <meta property="og:title" content="Tower Tumbler" />
    <meta property="og:description" content="基于物理的堆叠游戏，使用设备倾斜控制" />
    <meta property="og:image" content="https://xdanger.github.io/tower-tumbler/og-image.png" />
    <meta property="og:url" content="https://xdanger.github.io/tower-tumbler/" />
    
    <style>
        body {
            margin: 0;
            padding: 0;
            background: #000;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            font-family: Arial, sans-serif;
        }
        
        #game-canvas {
            max-width: 100vw;
            max-height: 100vh;
            border: none;
        }
        
        #loading {
            color: white;
            text-align: center;
        }
        
        .loading-progress {
            width: 200px;
            height: 4px;
            background: #333;
            border-radius: 2px;
            margin: 20px auto;
            overflow: hidden;
        }
        
        .loading-bar {
            height: 100%;
            background: linear-gradient(90deg, #4ade80, #3b82f6);
            width: 0%;
            transition: width 0.3s ease;
        }
    </style>
</head>
<body>
    <div id="loading">
        <h2>🏗️ Tower Tumbler</h2>
        <p>Loading game...</p>
        <div class="loading-progress">
            <div class="loading-bar" id="progress-bar"></div>
        </div>
        <p id="loading-status">Initializing...</p>
    </div>
    
    <canvas id="game-canvas" style="display: none;"></canvas>
    
    <script>
        // 加载进度跟踪
        let loadingProgress = 0;
        const progressBar = document.getElementById('progress-bar');
        const loadingStatus = document.getElementById('loading-status');
        
        function updateProgress(progress, status) {
            loadingProgress = Math.max(loadingProgress, progress);
            progressBar.style.width = loadingProgress + '%';
            loadingStatus.textContent = status;
        }
        
        // WASM 加载
        updateProgress(10, 'Loading WASM...');
        
        // 性能监控
        const startTime = performance.now();
        
        import('./tower_tumbler.js').then(async (wasm) => {
            updateProgress(50, 'Initializing game...');
            
            try {
                await wasm.default();
                updateProgress(80, 'Starting game...');
                
                // 隐藏加载界面，显示游戏
                setTimeout(() => {
                    document.getElementById('loading').style.display = 'none';
                    document.getElementById('game-canvas').style.display = 'block';
                    updateProgress(100, 'Ready\!');
                    
                    // 记录加载时间
                    const loadTime = performance.now() - startTime;
                    console.log(`Game loaded in ${loadTime.toFixed(2)}ms`);
                }, 500);
                
            } catch (error) {
                console.error('Failed to load game:', error);
                loadingStatus.textContent = 'Failed to load game. Please refresh.';
            }
        });
        
        // 错误追踪
        window.addEventListener('error', (event) => {
            console.error('Game error:', event.error);
        });
        
        // 离线支持提示
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('./sw.js');
        }
    </script>
</body>
</html>
```

### 4. PWA 配置

```json
// manifest.json
{
  "name": "Tower Tumbler",
  "short_name": "TowerTumbler",
  "description": "基于物理的堆叠游戏",
  "start_url": "./",
  "display": "fullscreen",
  "orientation": "portrait",
  "theme_color": "#000000",
  "background_color": "#000000",
  "icons": [
    {
      "src": "icons/icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "icons/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

### 5. Service Worker

```javascript
// sw.js
const CACHE_NAME = 'tower-tumbler-v1.0.0';
const urlsToCache = [
  './',
  './tower_tumbler.js',
  './tower_tumbler_bg.wasm',
  './manifest.json',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(urlsToCache))
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request)
      .then((response) => {
        // 缓存优先策略
        if (response) {
          return response;
        }
        return fetch(event.request);
      })
  );
});
```

### 6. 性能监控

```html
<\!-- 添加到 index.html -->
<script>
  // 简单的性能监控
  function trackPerformance() {
    if ('performance' in window) {
      window.addEventListener('load', () => {
        const perfData = performance.getEntriesByType('navigation')[0];
        
        // 发送性能数据（可选）
        console.log('Performance metrics:', {
          loadTime: perfData.loadEventEnd - perfData.fetchStart,
          domReady: perfData.domContentLoadedEventEnd - perfData.fetchStart,
          wasmSize: performance.getEntriesByName('./tower_tumbler_bg.wasm')[0]?.transferSize
        });
      });
    }
  }
  
  trackPerformance();
</script>
```

### 7. GitHub Pages 配置

```yaml
# .github/workflows/pages.yml (自动部署)
name: Deploy to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Install tools
        run: |
          cargo install trunk wasm-bindgen-cli
          npm install -g wasm-opt
      
      - name: Build
        run: |
          trunk build --release
          ./scripts/optimize-wasm.sh
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

## 📝 实现步骤

1. **发布准备**
   - [ ] 创建发布工作流
   - [ ] 编写构建脚本
   - [ ] 配置版本管理

2. **网站优化**
   - [ ] 创建生产模板
   - [ ] 配置 PWA 支持
   - [ ] 添加 Service Worker

3. **部署配置**
   - [ ] 设置 GitHub Pages
   - [ ] 配置自定义域名
   - [ ] 测试部署流程

4. **监控设置**
   - [ ] 添加性能监控
   - [ ] 配置错误追踪
   - [ ] 设置分析工具

5. **发布执行**
   - [ ] 创建 v0.1.0 标签
   - [ ] 触发自动部署
   - [ ] 验证线上版本

## ✅ 验收标准

1. **自动化部署**
   - [ ] 标签推送自动发布
   - [ ] 构建优化正常
   - [ ] 部署成功率 100%

2. **网站性能**
   - [ ] 加载时间 < 5s
   - [ ] WASM 大小 < 2.3MB
   - [ ] Lighthouse 分数 > 90

3. **用户体验**
   - [ ] 跨设备兼容
   - [ ] 离线功能正常
   - [ ] 错误处理完善

## 🚀 发布清单

- [ ] 所有核心功能完成
- [ ] 测试通过（单元 + E2E）
- [ ] 文档更新完整
- [ ] 性能指标达标
- [ ] 安全检查通过

## 📊 监控指标

1. **技术指标**
   - 加载时间
   - 错误率
   - 性能分数

2. **用户指标**
   - 访问量
   - 设备分布
   - 游戏时长

## 🎯 后续计划

- 建立发布节奏（双周发布）
- 收集用户反馈
- 持续性能优化
- 功能迭代规划
