### ISSUE TITLE
🚀 01 初始化 Cargo + Bevy + Trunk 架构 `setup/4-bevy-wasm`

### ISSUE THREAD

**Issue by xdanger** [xdanger/tower-tumbler#4]
## 🎯 任务目标

搭建 Tower Tumbler 项目的基础开发环境，配置 Rust + Bevy 0.14 + Rapier2D-wasm 技术栈，确保能够编译并运行一个基础的 WASM 应用。

## 📋 前置条件

- [ ] 安装 Rust 1.75+ (rustup)
- [ ] 安装 wasm-bindgen-cli (`cargo install wasm-bindgen-cli`)
- [ ] 安装 trunk (`cargo install trunk`)
- [ ] 安装 wasm-opt (`npm install -g wasm-opt`)

### 1. Cargo 项目结构
```toml
# Cargo.toml
[package]
name = "tower-tumbler"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_sprite", 
    "webgl2",
    "bevy_asset",
    "bevy_text",
    "bevy_ui",
    "png",  # 图片格式支持
]}
bevy_rapier2d = { version = "0.25", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Window",
    "Document", 
    "Element",
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "DeviceMotionEvent",
    "DeviceOrientationEvent",
    "Permissions",
    "Console",  # 调试输出
]}
console_error_panic_hook = "0.1"  # WASM panic 处理
uuid = { version = "1.6", features = ["v4", "js"] }  # 会话 ID

# 开发依赖
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.14", features = ["x11"] }  # 桌面开发

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"  # 减小二进制大小

[profile.dev.package."*"]
opt-level = 3  # 依赖库在开发模式下也优化
```

### 2. 项目目录结构
```
tower-tumbler/
├── Cargo.toml
├── Trunk.toml          # Trunk 配置
├── index.html          # 入口 HTML
├── src/
│   ├── main.rs         # 主入口
│   └── lib.rs          # WASM 库入口（用于 trunk）
├── assets/             # 游戏资源
│   ├── fonts/          # 字体文件
│   ├── textures/       # 纹理图片
│   └── .gitkeep
├── dist/               # 构建输出（.gitignore）
└── .cargo/
    └── config.toml     # Cargo 配置
```

### 3. Cargo 配置
```toml
# .cargo/config.toml
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[build]
target = "wasm32-unknown-unknown"
```

### 4. Trunk 配置
```toml
# Trunk.toml
[build]
target = "index.html"
dist = "dist"
public_url = "./"  # 相对路径，便于部署

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "wasm-opt -Oz -o dist/tower-tumbler_bg.wasm dist/tower-tumbler_bg.wasm"]

[serve]
port = 8080
open = true  # 自动打开浏览器
```

### 5. 基础 HTML 模板
```html
<\!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Tower Tumbler</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            overflow: hidden;
            background: #87CEEB;
            touch-action: none;
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            user-select: none;
        }
        
        #game-container {
            width: 100vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            position: relative;
        }
        
        canvas {
            max-width: 100%;
            max-height: 100%;
            touch-action: none;
        }
        
        /* 加载提示 */
        #loading {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
            font-family: sans-serif;
            font-size: 24px;
            text-align: center;
        }
        
        .loading-spinner {
            border: 3px solid rgba(255, 255, 255, 0.3);
            border-radius: 50%;
            border-top: 3px solid white;
            width: 40px;
            height: 40px;
            animation: spin 1s linear infinite;
            margin: 20px auto;
        }
        
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    </style>
</head>
<body>
    <div id="game-container">
        <div id="loading">
            <div>Tower Tumbler</div>
            <div class="loading-spinner"></div>
            <div>加载中...</div>
        </div>
        <link data-trunk rel="rust" data-wasm-opt="z" />
    </div>
    
    <script>
        // 隐藏加载提示
        window.addEventListener('load', () => {
            setTimeout(() => {
                const loading = document.getElementById('loading');
                if (loading) loading.style.display = 'none';
            }, 1000);
        });
        
        // 阻止默认触摸行为
        document.addEventListener('touchmove', (e) => e.preventDefault(), { passive: false });
    </script>
</body>
</html>
```

### 6. WASM 入口
```rust
// src/lib.rs
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn run() {
    // 设置 panic 处理
    #[cfg(target_arch = "wasm32")]
    console_error_panic_hook::set_once();
    
    // 启动游戏
    tower_tumbler::main();
}
```

### 7. 基础 Bevy 应用
```rust
// src/main.rs
use bevy::prelude::*;

#[cfg(target_arch = "wasm32")]
use bevy::window::WindowResolution;

pub fn main() {
    let mut app = App::new();
    
    // 窗口配置
    let window_plugin = WindowPlugin {
        primary_window: Some(Window {
            title: "Tower Tumbler".to_string(),
            #[cfg(target_arch = "wasm32")]
            canvas: Some("#game-container".to_string()),
            #[cfg(target_arch = "wasm32")]
            prevent_default_event_handling: true,
            #[cfg(target_arch = "wasm32")]
            resolution: WindowResolution::new(540., 960.), // 适配移动端
            #[cfg(not(target_arch = "wasm32"))]
            resolution: WindowResolution::new(540., 960.).with_scale_factor_override(1.0),
            ..default()
        }),
        ..default()
    };
    
    // 插件配置
    app.add_plugins(DefaultPlugins.set(window_plugin).set(
        // 优化日志输出
        bevy::log::LogPlugin {
            filter: "info,wgpu_core=warn,wgpu_hal=warn,tower_tumbler=debug".into(),
            level: bevy::log::Level::DEBUG,
        }
    ));
    
    // 添加启动系统
    app.add_systems(Startup, setup);
    
    // 诊断插件（开发模式）
    #[cfg(debug_assertions)]
    app.add_plugins(bevy::diagnostic::FrameTimeDiagnosticsPlugin);
    
    app.run();
}

fn setup(mut commands: Commands) {
    // 2D 相机
    commands.spawn(Camera2dBundle::default());
    
    // 测试精灵
    commands.spawn(SpriteBundle {
        sprite: Sprite {
            color: Color::rgb(0.25, 0.75, 0.25),
            custom_size: Some(Vec2::new(100.0, 100.0)),
            ..default()
        },
        ..default()
    });
    
    info\!("Tower Tumbler 启动成功！");
}
```

## 📊 验收标准

1. **构建成功**
   - [ ] `trunk build --release` 成功生成 WASM
   - [ ] 生成的 .wasm 文件 < 3MB (gzip 后)
   - [ ] 无编译警告
   - [ ] 构建时间 < 2 分钟（首次构建除外）

2. **运行验证**
   - [ ] `trunk serve` 启动本地服务器
   - [ ] 浏览器访问 http://localhost:8080 显示绿色方块
   - [ ] 控制台显示 "Tower Tumbler 启动成功！"
   - [ ] 加载动画正常显示和隐藏

3. **性能基准**
   - [ ] Chrome DevTools 显示 FPS ≥ 60
   - [ ] 初始加载时间 < 3s (本地)
   - [ ] WASM 内存使用 < 50MB

4. **浏览器兼容**
   - [ ] Chrome 109+ ✅
   - [ ] Safari 15+ ✅ 
   - [ ] Firefox 110+ ✅
   - [ ] 移动端 Chrome/Safari ✅

## 🚧 潜在问题

1. **WebGL 上下文丢失**
   - 监听 `webglcontextlost` 事件
   - 实现恢复机制（后续任务）

2. **WASM 加载失败**
   - index.html 中已提供加载提示
   - 错误时保持提示可见

3. **包体过大**
   - 已配置 `default-features = false`
   - 使用 wasm-opt -Oz 优化
   - 后续可考虑 wasm-pack 进一步优化

## 📝 开发笔记

- 使用 `web-sys` 而非 `stdweb` (已弃用)
- Bevy 0.14 的 `webgl2` feature 必须开启
- `console_error_panic_hook` 让 panic 信息在浏览器控制台可见
- 桌面开发时自动启用 x11 feature

## 🔗 参考资源

- [Bevy WASM Example](https://github.com/bevyengine/bevy/tree/main/examples/wasm)
- [Trunk Documentation](https://trunkrs.dev/)
- [wasm-bindgen Book](https://rustwasm.github.io/wasm-bindgen/book/)
- [Bevy 0.14 Migration Guide](https://bevyengine.org/learn/migration-guides/0.13-0.14/)

---

**任务类型**: 🏗️ Setup
**预计工时**: 2-3 小时
**依赖任务**: 无
**优先级**: 🔴 Critical (关键路径)

**Comment by xdanger** [comment]
## 完成记录 - 关键技术信息

### ✅ 成功解决 getrandom 版本冲突

**问题根因**：

- getrandom 0.2 与 0.3 在 WASM 目标下都导出同名 JS 绑定 `__wbindgen_getrandom_js`
- Bevy 0.14 依赖 rand 0.8 → getrandom 0.2
- bevy_rapier2d 0.27 部分依赖链拉入 rand 0.9 → getrandom 0.3
- 两版本同时存在导致 WASM 链接冲突

**解决方案 - 全线升级 getrandom 0.3**：

```toml
[dependencies]
rand = "0.9"  # 强制使用新版本
getrandom = { version = "0.3", features = ["wasm_js"] }
bevy = { version = "0.14", features = ["bevy_state", ...] }
bevy_rapier2d = { version = "0.27", features = ["wasm-bindgen", "debug-render-2d"] }
```

WASM 配置：

```toml
# .cargo/config.toml
[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis", "--cfg=getrandom_backend=\"wasm_js\""]
```

🎯 最终架构成果

验证通过：

- ✅ cargo check --target wasm32-unknown-unknown
- ✅ trunk build --release 完整 WASM 构建
- ✅ 物理引擎 (Rapier2D) 正常集成
- ✅ 设备权限处理完整实现

核心配置文件：

- Cargo.toml - 完整依赖配置，解决版本冲突
- Trunk.toml - WASM 构建工具配置
- index.html - 设备倾斜权限处理
- .cargo/config.toml - WASM 目标优化

模块架构：

```plaintext
src/
├── lib.rs # 主入口，States 管理
├── main.rs # 可执行入口
├── core/ # 游戏核心逻辑
├── input/ # 输入处理 (倾斜 + 键盘)
├── physics/ # Rapier2D 物理引擎
└── ui/ # Bevy UI 界面
```

🔧 关键技术点

1. getrandom 0.3 特性：使用 wasm_js 而非旧版的 js
2. RUSTFLAGS 必需：getrandom 0.3 需要显式 backend 配置
3. Bevy States: 需要启用 bevy_state 特性，使用 States derive
4. Trunk 目标：使用 data-target-name="tower_tumbler" 避免冲突
5. crate-type: ["cdylib", "rlib"] 支持 WASM 和本地构建

📊 构建验证

性能指标：

- WASM 包大小：约 2.3MB (使用 wasm-opt)
- 编译时间：~2 分钟 (release 模式)
- 依赖数量：389 个 crates

开发环境就绪：

- 开发服务器：trunk serve (localhost:8080)
- 热重载支持
- 浏览器调试工具集成

🚀 下一步开发准备

架构完全就绪，可以开始：

- Issue #5: 生成地面刚体 + 精灵
- Issue #6: 周期性生成随机大小箱子实体
- Issue #7: 监听碰撞，静态化，计算偏差

重要：此解决方案为 Rust/Bevy/WASM 生态系统中 getrandom 版本冲突提供了标准参考。
